import { type NextPage } from "next";
import Head from "next/head";
import {
  Button,
  Card,
  CardActions,
  CardContent,
  Container,
  Typography,
} from "@mui/material";
import Grid from "@mui/material/Unstable_Grid2";
import { Box } from "@mui/system";
import ShoppingCartIcon from "@mui/icons-material/ShoppingCart";
import React, { useEffect } from "react";
import { useMutation, useQuery } from "react-query";
import { CartResponse, Product } from "./api/cart";
import { createEventBus } from "../EventBus";

const products: Product[] = [
  {
    name: "Bread",
    price: 10_000,
  },
  {
    name: "Milk",
    price: 12_000,
  },
];

const eventBus = createEventBus();

function Nav() {
  const { data, refetch } = useQuery<CartResponse>("cart", () =>
    fetch("/api/cart").then((res) => res.json())
  );

  const itemsCount = data?.items.length || 0;

  useEffect(() => {
    const unsubscribeUpdateCart = eventBus.on("updateCart", () => {
      refetch();
    });

    return () => {
      unsubscribeUpdateCart();
    };
  }, []);

  return (
    <Box component="nav" display="flex" padding={2}>
      <Button variant="contained" startIcon={<ShoppingCartIcon />}>
        Cart ({itemsCount})
      </Button>
    </Box>
  );
}

function ProductCard({ product }: { product: Product }) {
  const { mutateAsync, isLoading } = useMutation((product: Product) =>
    fetch("/api/cart", { method: "POST", body: JSON.stringify(product) })
  );

  async function handleAddToCart() {
    await mutateAsync(product);
    eventBus.emit("updateCart", []);
  }

  return (
    <Grid>
      <Card>
        <CardContent>
          <Typography variant="h5" component="h3">
            {product.name}
          </Typography>
          <Typography variant="body2" component="p">
            {product.price}
          </Typography>
        </CardContent>
        <CardActions>
          <Button
            variant="contained"
            onClick={handleAddToCart}
            disabled={isLoading}
          >
            Add to cart
          </Button>
        </CardActions>
      </Card>
    </Grid>
  );
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component="main" maxWidth="sm" m="auto" px={2}>
        <Nav />
        <Container>
          <Typography variant="h2" component="h1" mb={4}>
            Click add to cart and see the cart count update
          </Typography>
          <Typography variant="body1" mb={4}>
            The cart is updated using{" "}
            <a
              target="_blank"
              href="https://betterprogramming.pub/how-to-use-event-bus-in-react-architecture-f90485477647"
              rel="noopener noreferrer"
            >
              event bus
            </a>
            .
          </Typography>
          <Grid container spacing={2}>
            {products.map((product) => (
              <ProductCard product={product} />
            ))}
          </Grid>
        </Container>
      </Box>
    </>
  );
};

export default Home;
